name: Run Selenium Test

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 9 * * 0-4"  # Run at 11:00 AM from Sunday to Thursday

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          cache: maven
          distribution: "adopt"

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Run Selenium Tests and Generate Report
        run: |
          mvn clean test -Denvironment=ip
        continue-on-error: true

      - name: Archive artifacts
        id: generate-report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/

  send-email:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

      - name: Download screenshots
        uses: actions/download-artifact@v2
        with:
          name: test-screenshots
          path: target/screenshots

      - name: Check test results and find failed method
        id: check-test-results
        run: |
          failures=$(grep -r -l "FAILED" target/surefire-reports/*.txt || true)
          failed_method=$(basename "${failures}" .txt)
          echo "::set-output name=failed-method::$failed_method"

      - name: Send email on failure with screenshot
        if: ${{ steps.check-test-results.outputs.failed-method != '' }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: "ahmedali@azka.com,aabdelaziz@azka.com"
          from: "azkatestingteam@gmail.com"
          subject: "Qdaa Store Test Results - Failure"
          body: |
            <p>
            Dear Eng. Ahmed,
            The Selenium test results indicate a failure in method '${{ steps.check-test-results.outputs.failed-method }}'. Please review the attached HTML report and screenshot.
            </p>
          attachments: |
            target/surefire-reports/emailable-report.html
            target/screenshots/${{ steps.check-test-results.outputs.failed-method }}.png

      - name: Send email on success
        if: ${{ steps.check-test-results.outputs.failed-method == '' }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: "aabdelaziz@azka.com"
          from: "azkatestingteam@gmail.com"
          subject: "Qdaa Store Test Results - Success"
          body: |
            <p>
            Dear Eng. Ahmed,
            The Selenium test results indicate a success. Please find the attached HTML report.
            </p>
          attachments: target/surefire-reports/emailable-report.html
